[package]
name = "weather_api_rust"
version = "0.3.3"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

[package.metadata.deb]
name = "weather-api-rust"
priority = "optional"
section = "rust"
provides = "sync-app-rust"
extended-description = """\
Weather API."""

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
weather_util_rust = "0.5"
anyhow = "1.0"
cached = "0.22"
thiserror = "1.0"
actix-web = "3.3"
actix-rt = "1.1"
tokio = {version="0.3", features=["full"]}
lazy_static = "1.4"
serde = {version="1.0", features=["derive"]}
serde_json = "1.0"
maplit = "1.0"
dotenv = "0.15"
dirs = "3.0"
chrono = "0.4"
envy = "0.4"
handlebars = "3.5"

[dev-dependencies]
reqwest = {version = "0.10", features=["cookies", "rustls-tls", "gzip", "json"]}
tokio-compat-02 = "0.1"
chrono-tz = "0.5"

[[bin]]
name = "weather-api-rust"
path = "src/main.rs"
doc = false
