[package]
name = "weather_api_rust"
version = "0.7.5"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

[package.metadata.deb]
name = "weather-api-rust"
priority = "optional"
section = "rust"
provides = "sync-app-rust"
extended-description = """\
Weather API."""

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "weather_api_common",
    "weather_app_desktop",
]
exclude = [
    "weather_app_wasm",
    "weather_api_wasm"
]

[dependencies]
weather_api_common = {path = "weather_api_common/"}
weather_util_rust = {version="0.15", default-features=false, features=["cli"]}
time = {version="0.3", features=["serde-human-readable", "macros", "formatting"]}
anyhow = "1.0"
cached = "0.42"
thiserror = "1.0"
http = "0.2"
tokio = {version="1.24", features=["full"]}
lazy_static = "1.4"
serde = {version="1.0", features=["derive"]}
serde_json = "1.0"
serde_yaml = "0.9"
dotenvy = "0.15"
dirs = "4.0"
envy = "0.4"
rweb = {version="0.15", features=["openapi"]}
stack-string = {version="0.8", features=["rweb-openapi"]}
isocountry = "0.3"
derive_more = "0.99"
indexmap = "1.9"
rweb-helper = {git = "https://github.com/ddboline/rweb_helper.git", tag="0.4.16", features=["time"]}
dioxus = "0.3"
dioxus-ssr = "0.3"
log = "0.4"
env_logger = "0.10"
parking_lot = "0.12"

[dev-dependencies]
reqwest = {version = "0.11", features=["cookies", "rustls-tls", "gzip", "json"], default-features=false}
time-tz = "1.0"

[[bin]]
name = "weather-api-rust"
path = "src/main.rs"
doc = false
