[package]
name = "weather_api_rust"
version = "0.1.5"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
weather_util_rust = "0.1.13"
actix-rt = "1.0"
anyhow = "1.0"
cached = "0.11"
thiserror = "1.0"
actix-web = "2.0"
tokio = {version="0.2", features=["full"]}
lazy_static = "1.4"
serde = {version="1.0", features=["derive"]}
serde_json = "1.0"
maplit = "1.0"
dotenv = "0.15"
dirs = "2.0"

[[bin]]
name = "weather-api-rust"
path = "src/main.rs"
doc = false
