[package]
name = "weather_api_rust"
version = "0.5.4"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

[package.metadata.deb]
name = "weather-api-rust"
priority = "optional"
section = "rust"
provides = "sync-app-rust"
extended-description = """\
Weather API."""

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
weather_util_rust = "0.7"
anyhow = "1.0"
cached = "0.23"
thiserror = "1.0"
http = "0.2"
tokio = {version="1.2", features=["full"]}
lazy_static = "1.4"
serde = {version="1.0", features=["derive"]}
serde_json = "1.0"
maplit = "1.0"
dotenv = "0.15"
dirs = "3.0"
chrono = "0.4"
envy = "0.4"
handlebars = "3.5"
rweb = "0.12"
stack-string = "0.2"
isocountry = "0.3"

[dev-dependencies]
reqwest = {version = "0.11", features=["cookies", "rustls-tls", "gzip", "json"]}
chrono-tz = "0.5"
env_logger = "0.8"

[[bin]]
name = "weather-api-rust"
path = "src/main.rs"
doc = false
