[package]
name = "weather_api_wasm"
version = "0.7.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
weather_api_common = {path = "../weather_api_common/"}
dioxus = "0.3"
dioxus-web = "0.3"
# golde = {git = "https://github.com/ddboline/golde.git", branch="main"}
fermi = "0.3"
log = "0.4"
# doson = "0.1"
wasm-logger = "0.2"
console_error_panic_hook = "0.1"
wasm-bindgen = "0.2"
# maplit = "1.0"
http = "0.2"
url = "2.3"
serde = "1.0"
serde_json = "1.0"
web-sys = {version="0.3", features=["Storage", "Window", "Request", "RequestInit", "Response"]}
weather_util_rust = {version="0.15", default-features=false}
wasm-bindgen-futures = "0.4"
serde-wasm-bindgen = "0.4"
isocountry = "0.3"
time = {version="0.3", features=["serde-human-readable", "macros", "formatting"]}
