[package]
name = "weather_api_common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
weather_util_rust = {version="0.14", features=["stack-string"]}
dioxus = "0.2"
stack-string = {version="0.7", features=["rweb-openapi"]}
time = {version="0.3", features=["serde-human-readable", "macros", "formatting"]}
anyhow = "1.0"
serde = {version="1.0", features=["derive"]}
serde_json = "1.0"
futures-channel = "0.3"
url = "2.3"
log = "0.4"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
reqwest = {version="0.11", features=["rustls-tls", "json"]}