name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: rustup update

    - name: Clippy
      run: cargo clippy

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: |
        cargo test --verbose && \
        cargo install cargo-tarpaulin --version 0.18.0-alpha3 && \
        cargo tarpaulin --verbose --all-features --workspace --out Xml --avoid-cfg-tarpaulin
      env:
        API_KEY: ${{secrets.API_KEY}}
        API_ENDPOINT: api.openweathermap.org

    - name: Upload to codecov.io
      uses: codecov/codecov-action@v2.1.0
      with:
        token: ${{secrets.CODECOV_TOKEN}}

    - name: Archive code coverage results
      uses: actions/upload-artifact@v1
      with:
        name: code-coverage-report
        path: cobertura.xml
